export enum ProjectManagerResponseStatus {
    BAD_REQUEST = "BAD_REQUEST",
    PROJECT_OPENED = "PROJECT_OPENED",
    PROJECT_CREATED = "PROJECT_CREATED",
    PROJECT_UPDATED = "PROJECT_UPDATED",
    PROJECT_DELETED = "PROJECT_DELETED",
}