export enum StatusCode {
    OK = 'OK',
    FAILED_COMPILATION = 'FAILED_COMPILATION',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    SUCCESSFUL_COMPILATION = 'SUCCESSFUL_COMPILATION',
    SUCCESSFUL_EXECUTION = 'SUCCESSFUL_EXECUTION',
    RUNTIME_ERROR = 'RUNTIME_ERROR',
    TIME_LIMIT_EXCEEDED = 'TIME_LIMIT_EXCEEDED'
}